name: CI

on:
  push:
    branches:
      - v0/criacao-testes-iniciais  # ou o nome da sua branch padrão

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # ou a versão de Python que você está usando

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          python manage.py test accounts.tests --settings=conecta_cientifica.settings_test
